name: Nasa Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.10.0

      - run: npm install
      - run: npm install --prefix Client
      - run: npm run build --prefix Client
      - run: npm test
